name: Static Analysis Scanner
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch: {}

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Verify module
        run: go mod verify

      - name: Build go App
        run: go build -v ./...

      - name: Generate coverage out
        run: go test -coverprofile=./coverage.out ./service/...